[general]
device = "mps"
logs = "../logs/logs"
chunks_all = "../logs/chunks_all"
chunks_last = "../logs/chunks_last"

[generation]
model = "llama-3.3-70b-versatile"

[embedding]
model = "jinaai/jina-embeddings-v2-base-en"

[retrieval]
k_nearest = 10
history = 10
model = "llama-3.1-8b-instant"

[session]
host="localhost"
port=6379
expiry=20

